name: Run_Staging
on:
  workflow_dispatch:
  schedule:
   - cron: "*/5 * * * *"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: staging
      - name: Branch
        run: cat test.txt
