name: Run_Staging
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  workflow_dispatch:
  schedule:
    - cron: '*/6 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v1
        with:
          ref: staging
#      - name: Branch name
#        run: echo running on branch ${GITHUB_REF##*/}