name: Run_Staging
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  schedule:
    - cron: '*/6 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Git checkout
        uses: actions/checkout@v1
#        with:
#          ref: staging
#      - name: Branch name
#        run: echo running on branch ${GITHUB_REF##*/}